#!/usr/bin/env bash
# Changes port in Nginx to listen on port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(awk '{print $1}' /run/nginx.pid)"
