#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd, using the while loop + IFS.
while IFS=: read -r user pw uid gid gecos home shell;
do
    echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pw, more info about the user here: $gecos"
done < /etc/passwd