#!/usr/bin/env bash
# This script is displaying "Best School" 10 times. If 9, say Hi!
i=1
while [ $i -lt 9 ]
do
    if [ $i -eq 4 ];
    then
        echo "bad luck"
    elif [ $i -eq 7 ];
    then
        echo "good luck"

    fi
    echo "Best School"
    (( i++ ))
done